# Generated by Django 3.1.3 on 2021-02-21 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0010_auto_20210221_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Facebook_url',
            new_name='facebook_url',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Instagram_url',
            new_name='instagram_url',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='LinkedIn_url',
            new_name='linkedIn_url',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Twitter_url',
            new_name='twitter_url',
        ),
    ]
